common_name: "Trost_Selfsigned_ca"
organization:
  - "Trost"
organizational_unit:
  - "Trost_ca"
country:
  - "VN"
province:
  - "Hanoi"
locality:
  - "Hanoi"
postal_code:
  - "100000"
dns_names:
  - "localhost"
ip_addresses:
  - "localhost"
validity_period: "8760h"